import pkg.*;
import java.util.Scanner;
import java.util.Random;


class starter {
	public static void main(String args[]) {
		// Your code goes below here
		
		NPC randomDude = new NPC("generic name", "how do u do fellow NPCs?");
		randomDude.createNPC();
		
	}
}
	
class NPC {
	String name;
	int autoGeneratedRandomNumber;
	double same;
	float ditto;
	String voiceline;
	
	NPC(String a, String b) {
		name = a;
		voiceline = b;
	}
	
	void createNPC() {
		System.out.println("Name: " + name);
		System.out.println("Stats: " + autoGeneratedRandomNumber);
		System.out.println("Appearance: " + same);
		System.out.println("???: " + ditto);
		System.out.println("");
		System.out.println(name + ": " + voiceline);
	}
		
		
		
		
		
		
		
		
		
		//		isItRight("this is correct");

		
		
		
		
		
		/*	public static boolean isItRight(String wrong) {
		if(wrong.equals("this is correct")) {
			return true;
		}
		if(wrong.equals("this is incorrect")) {
			return false;
		}
		return false;
	}
}*/














		
		
		
		
		
		
		
		
//		System.out.print("What will the output be ??? \\n + .\" hi \" \n ");
//		System.out.println("hi?");


//		System.out.println(1 % (2 + 5) * 2 % 3 / 8 + "1 * 10" + 999);

	}